begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|composite
package|;
end_package

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|FluentIterable
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|Blob
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|PropertyState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|Type
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|commons
operator|.
name|PathUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|memory
operator|.
name|EmptyNodeState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|memory
operator|.
name|MemoryNodeBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|state
operator|.
name|NodeBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|state
operator|.
name|NodeState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import static
name|java
operator|.
name|lang
operator|.
name|Long
operator|.
name|MAX_VALUE
import|;
end_import

begin_import
import|import static
name|java
operator|.
name|util
operator|.
name|Collections
operator|.
name|singleton
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|composite
operator|.
name|CompositeNodeState
operator|.
name|STOP_COUNTING_CHILDREN
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|composite
operator|.
name|CompositeNodeState
operator|.
name|accumulateChildSizes
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|memory
operator|.
name|EmptyNodeState
operator|.
name|MISSING_NODE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|state
operator|.
name|AbstractNodeState
operator|.
name|checkValidName
import|;
end_import

begin_class
class|class
name|CompositeNodeBuilder
implements|implements
name|NodeBuilder
block|{
specifier|private
specifier|final
specifier|static
name|Logger
name|LOG
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|CompositeNodeBuilder
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|private
specifier|final
name|CompositionContext
name|ctx
decl_stmt|;
specifier|private
specifier|final
name|NodeMap
argument_list|<
name|NodeBuilder
argument_list|>
name|nodeBuilders
decl_stmt|;
name|CompositeNodeBuilder
parameter_list|(
name|NodeMap
argument_list|<
name|NodeBuilder
argument_list|>
name|nodeBuilders
parameter_list|,
name|CompositionContext
name|ctx
parameter_list|)
block|{
name|this
operator|.
name|ctx
operator|=
name|ctx
expr_stmt|;
name|this
operator|.
name|nodeBuilders
operator|=
name|nodeBuilders
expr_stmt|;
name|ctx
operator|.
name|getNodeBuilderMonitor
argument_list|()
operator|.
name|onCreateNodeObject
argument_list|(
name|getPath
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|NodeBuilder
name|getNodeBuilder
parameter_list|(
name|MountedNodeStore
name|mns
parameter_list|)
block|{
return|return
name|nodeBuilders
operator|.
name|get
argument_list|(
name|mns
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|CompositeNodeState
name|getNodeState
parameter_list|()
block|{
return|return
operator|new
name|CompositeNodeState
argument_list|(
name|getPath
argument_list|()
argument_list|,
name|nodeBuilders
operator|.
name|getAndApply
argument_list|(
operator|(
name|mns
operator|,
name|b
operator|)
operator|->
name|b
operator|.
name|exists
argument_list|()
condition|?
name|b
operator|.
name|getNodeState
argument_list|()
else|:
name|MISSING_NODE
argument_list|)
argument_list|,
name|ctx
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|CompositeNodeState
name|getBaseState
parameter_list|()
block|{
return|return
operator|new
name|CompositeNodeState
argument_list|(
name|getPath
argument_list|()
argument_list|,
name|nodeBuilders
operator|.
name|getAndApply
argument_list|(
parameter_list|(
name|mns
parameter_list|,
name|b
parameter_list|)
lambda|->
name|b
operator|.
name|getBaseState
argument_list|()
argument_list|)
argument_list|,
name|ctx
argument_list|)
return|;
block|}
comment|// node or property-related methods ; directly delegate to wrapped builder
annotation|@
name|Override
specifier|public
name|boolean
name|exists
parameter_list|()
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|exists
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isNew
parameter_list|()
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|isNew
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isNew
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|isNew
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isModified
parameter_list|()
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|isModified
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isReplaced
parameter_list|()
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|isReplaced
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isReplaced
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|isReplaced
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|long
name|getPropertyCount
parameter_list|()
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|getPropertyCount
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|Iterable
argument_list|<
name|?
extends|extends
name|PropertyState
argument_list|>
name|getProperties
parameter_list|()
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|getProperties
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|hasProperty
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|hasProperty
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|PropertyState
name|getProperty
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|getProperty
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|getBoolean
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|getBoolean
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|getString
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|getString
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|getName
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|getName
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|Iterable
argument_list|<
name|String
argument_list|>
name|getNames
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|getNames
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|NodeBuilder
name|setProperty
parameter_list|(
name|PropertyState
name|property
parameter_list|)
throws|throws
name|IllegalArgumentException
block|{
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|setProperty
argument_list|(
name|property
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
parameter_list|<
name|T
parameter_list|>
name|NodeBuilder
name|setProperty
parameter_list|(
name|String
name|name
parameter_list|,
name|T
name|value
parameter_list|)
throws|throws
name|IllegalArgumentException
block|{
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|setProperty
argument_list|(
name|name
argument_list|,
name|value
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
parameter_list|<
name|T
parameter_list|>
name|NodeBuilder
name|setProperty
parameter_list|(
name|String
name|name
parameter_list|,
name|T
name|value
parameter_list|,
name|Type
argument_list|<
name|T
argument_list|>
name|type
parameter_list|)
throws|throws
name|IllegalArgumentException
block|{
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|setProperty
argument_list|(
name|name
argument_list|,
name|value
argument_list|,
name|type
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|NodeBuilder
name|removeProperty
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|removeProperty
argument_list|(
name|name
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
comment|// child-related methods, require composition
annotation|@
name|Override
specifier|public
name|long
name|getChildNodeCount
parameter_list|(
specifier|final
name|long
name|max
parameter_list|)
block|{
name|List
argument_list|<
name|MountedNodeStore
argument_list|>
name|contributingStores
init|=
name|ctx
operator|.
name|getContributingStoresForBuilders
argument_list|(
name|getPath
argument_list|()
argument_list|,
name|nodeBuilders
argument_list|)
decl_stmt|;
if|if
condition|(
name|contributingStores
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
return|return
literal|0
return|;
comment|// this shouldn't happen
block|}
elseif|else
if|if
condition|(
name|contributingStores
operator|.
name|size
argument_list|()
operator|==
literal|1
condition|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|getChildNodeCount
argument_list|(
name|max
argument_list|)
return|;
block|}
else|else
block|{
comment|// Count the children in each contributing store.
return|return
name|accumulateChildSizes
argument_list|(
name|FluentIterable
operator|.
name|from
argument_list|(
name|contributingStores
argument_list|)
operator|.
name|transformAndConcat
argument_list|(
name|mns
lambda|->
block|{
name|NodeBuilder
name|node
init|=
name|nodeBuilders
operator|.
name|get
argument_list|(
name|mns
argument_list|)
decl_stmt|;
if|if
condition|(
name|node
operator|.
name|getChildNodeCount
argument_list|(
name|max
argument_list|)
operator|==
name|MAX_VALUE
condition|)
block|{
return|return
name|singleton
argument_list|(
name|STOP_COUNTING_CHILDREN
argument_list|)
return|;
block|}
else|else
block|{
return|return
name|FluentIterable
operator|.
name|from
argument_list|(
name|node
operator|.
name|getChildNodeNames
argument_list|()
argument_list|)
operator|.
name|filter
argument_list|(
name|e
lambda|->
name|belongsToStore
argument_list|(
name|mns
argument_list|,
name|e
argument_list|)
argument_list|)
return|;
block|}
block|}
argument_list|)
argument_list|,
name|max
argument_list|)
return|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|Iterable
argument_list|<
name|String
argument_list|>
name|getChildNodeNames
parameter_list|()
block|{
return|return
name|FluentIterable
operator|.
name|from
argument_list|(
name|ctx
operator|.
name|getContributingStoresForBuilders
argument_list|(
name|getPath
argument_list|()
argument_list|,
name|nodeBuilders
argument_list|)
argument_list|)
operator|.
name|transformAndConcat
argument_list|(
name|mns
lambda|->
name|FluentIterable
operator|.
name|from
argument_list|(
name|nodeBuilders
operator|.
name|get
argument_list|(
name|mns
argument_list|)
operator|.
name|getChildNodeNames
argument_list|()
argument_list|)
operator|.
name|filter
argument_list|(
name|e
lambda|->
name|belongsToStore
argument_list|(
name|mns
argument_list|,
name|e
argument_list|)
argument_list|)
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|hasChildNode
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|String
name|childPath
init|=
name|simpleConcat
argument_list|(
name|getPath
argument_list|()
argument_list|,
name|name
argument_list|)
decl_stmt|;
name|MountedNodeStore
name|mountedStore
init|=
name|ctx
operator|.
name|getOwningStore
argument_list|(
name|childPath
argument_list|)
decl_stmt|;
return|return
name|nodeBuilders
operator|.
name|get
argument_list|(
name|mountedStore
argument_list|)
operator|.
name|hasChildNode
argument_list|(
name|name
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|NodeBuilder
name|child
parameter_list|(
name|String
name|name
parameter_list|)
block|{
if|if
condition|(
name|hasChildNode
argument_list|(
name|name
argument_list|)
condition|)
block|{
return|return
name|getChildNode
argument_list|(
name|name
argument_list|)
return|;
block|}
else|else
block|{
return|return
name|setChildNode
argument_list|(
name|name
argument_list|)
return|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|NodeBuilder
name|getChildNode
parameter_list|(
specifier|final
name|String
name|name
parameter_list|)
block|{
name|String
name|childPath
init|=
name|simpleConcat
argument_list|(
name|getPath
argument_list|()
argument_list|,
name|name
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|ctx
operator|.
name|shouldBeComposite
argument_list|(
name|childPath
argument_list|)
condition|)
block|{
name|MountedNodeStore
name|mns
init|=
name|ctx
operator|.
name|getOwningStore
argument_list|(
name|childPath
argument_list|)
decl_stmt|;
name|ctx
operator|.
name|getNodeBuilderMonitor
argument_list|()
operator|.
name|onSwitchNodeToNative
argument_list|(
name|mns
operator|.
name|getMount
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|nodeBuilders
operator|.
name|get
argument_list|(
name|mns
argument_list|)
operator|.
name|getChildNode
argument_list|(
name|name
argument_list|)
return|;
block|}
return|return
operator|new
name|CompositeNodeBuilder
argument_list|(
name|nodeBuilders
operator|.
name|lazyApply
argument_list|(
parameter_list|(
name|mns
parameter_list|,
name|b
parameter_list|)
lambda|->
name|b
operator|.
name|getChildNode
argument_list|(
name|name
argument_list|)
argument_list|)
argument_list|,
name|ctx
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|NodeBuilder
name|setChildNode
parameter_list|(
name|String
name|name
parameter_list|)
throws|throws
name|IllegalArgumentException
block|{
return|return
name|setChildNode
argument_list|(
name|name
argument_list|,
name|EmptyNodeState
operator|.
name|EMPTY_NODE
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|NodeBuilder
name|setChildNode
parameter_list|(
specifier|final
name|String
name|name
parameter_list|,
name|NodeState
name|nodeState
parameter_list|)
block|{
if|if
condition|(
operator|!
name|exists
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"This builder does not exist: "
operator|+
name|PathUtils
operator|.
name|getName
argument_list|(
name|getPath
argument_list|()
argument_list|)
argument_list|)
throw|;
block|}
name|String
name|childPath
init|=
name|simpleConcat
argument_list|(
name|getPath
argument_list|()
argument_list|,
name|name
argument_list|)
decl_stmt|;
name|MountedNodeStore
name|childStore
init|=
name|ctx
operator|.
name|getOwningStore
argument_list|(
name|childPath
argument_list|)
decl_stmt|;
if|if
condition|(
name|childStore
operator|!=
name|ctx
operator|.
name|getGlobalStore
argument_list|()
operator|&&
operator|!
name|nodeBuilders
operator|.
name|get
argument_list|(
name|childStore
argument_list|)
operator|.
name|exists
argument_list|()
condition|)
block|{
comment|// if it doesn't exist in the read-only repository, create it in the global repository
comment|// (needed for example for a new index)
if|if
condition|(
name|LOG
operator|.
name|isDebugEnabled
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Creating node in the global store; will become invisible once overlayed: "
operator|+
name|childPath
argument_list|)
expr_stmt|;
block|}
name|childStore
operator|=
name|ctx
operator|.
name|getGlobalStore
argument_list|()
expr_stmt|;
block|}
specifier|final
name|NodeBuilder
name|childBuilder
init|=
name|nodeBuilders
operator|.
name|get
argument_list|(
name|childStore
argument_list|)
operator|.
name|setChildNode
argument_list|(
name|name
argument_list|,
name|nodeState
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|ctx
operator|.
name|shouldBeComposite
argument_list|(
name|childPath
argument_list|)
condition|)
block|{
return|return
name|childBuilder
return|;
block|}
return|return
operator|new
name|CompositeNodeBuilder
argument_list|(
name|nodeBuilders
operator|.
name|lazyApply
argument_list|(
parameter_list|(
name|mns
parameter_list|,
name|b
parameter_list|)
lambda|->
name|b
operator|.
name|getChildNode
argument_list|(
name|name
argument_list|)
argument_list|)
operator|.
name|replaceNode
argument_list|(
name|childStore
argument_list|,
name|childBuilder
argument_list|)
argument_list|,
name|ctx
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|remove
parameter_list|()
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|remove
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|moveTo
parameter_list|(
name|NodeBuilder
name|newParent
parameter_list|,
name|String
name|newName
parameter_list|)
block|{
return|return
name|getWrappedNodeBuilder
argument_list|()
operator|.
name|moveTo
argument_list|(
name|newParent
argument_list|,
name|newName
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|Blob
name|createBlob
parameter_list|(
name|InputStream
name|stream
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|ctx
operator|.
name|createBlob
argument_list|(
name|stream
argument_list|)
return|;
block|}
specifier|private
name|NodeBuilder
name|getWrappedNodeBuilder
parameter_list|()
block|{
return|return
name|nodeBuilders
operator|.
name|get
argument_list|(
name|ctx
operator|.
name|getGlobalStore
argument_list|()
argument_list|)
return|;
block|}
name|String
name|getPath
parameter_list|()
block|{
return|return
operator|(
operator|(
name|MemoryNodeBuilder
operator|)
name|getWrappedNodeBuilder
argument_list|()
operator|)
operator|.
name|getPath
argument_list|()
return|;
block|}
specifier|private
name|boolean
name|belongsToStore
parameter_list|(
name|MountedNodeStore
name|mns
parameter_list|,
name|String
name|childName
parameter_list|)
block|{
return|return
name|ctx
operator|.
name|belongsToStore
argument_list|(
name|mns
argument_list|,
name|getPath
argument_list|()
argument_list|,
name|childName
argument_list|)
return|;
block|}
comment|/**      * This simplified version of {@link PathUtils#concat(String, String)} method      * assumes that the parentPath is valid and not null, while the second argument      * is just a name (not a subpath).      *      * @param parentPath the parent path      * @param name       name to concatenate      * @return the parentPath concatenated with name      */
specifier|static
name|String
name|simpleConcat
parameter_list|(
name|String
name|parentPath
parameter_list|,
name|String
name|name
parameter_list|)
block|{
name|checkValidName
argument_list|(
name|name
argument_list|)
expr_stmt|;
if|if
condition|(
name|PathUtils
operator|.
name|denotesRoot
argument_list|(
name|parentPath
argument_list|)
condition|)
block|{
return|return
name|parentPath
operator|+
name|name
return|;
block|}
else|else
block|{
return|return
operator|new
name|StringBuilder
argument_list|(
name|parentPath
operator|.
name|length
argument_list|()
operator|+
name|name
operator|.
name|length
argument_list|()
operator|+
literal|1
argument_list|)
operator|.
name|append
argument_list|(
name|parentPath
argument_list|)
operator|.
name|append
argument_list|(
literal|'/'
argument_list|)
operator|.
name|append
argument_list|(
name|name
argument_list|)
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
block|}
end_class

end_unit

