begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|query
operator|.
name|index
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertTrue
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertFalse
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|query
operator|.
name|ast
operator|.
name|ComparisonImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
specifier|public
class|class
name|LikePatternTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|pattern
parameter_list|()
block|{
name|pattern
argument_list|(
literal|"%_"
argument_list|,
literal|"X"
argument_list|,
literal|""
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|pattern
argument_list|(
literal|"A%"
argument_list|,
literal|"A"
argument_list|,
literal|"X"
argument_list|,
literal|"A"
argument_list|,
literal|"B"
argument_list|)
expr_stmt|;
name|pattern
argument_list|(
literal|"A%%"
argument_list|,
literal|"A"
argument_list|,
literal|"X"
argument_list|,
literal|"A"
argument_list|,
literal|"B"
argument_list|)
expr_stmt|;
name|pattern
argument_list|(
literal|"%\\_%"
argument_list|,
literal|"A_A"
argument_list|,
literal|"AAA"
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
specifier|private
specifier|static
name|void
name|pattern
parameter_list|(
name|String
name|pattern
parameter_list|,
name|String
name|match
parameter_list|,
name|String
name|noMatch
parameter_list|,
name|String
name|lower
parameter_list|,
name|String
name|upper
parameter_list|)
block|{
name|ComparisonImpl
operator|.
name|LikePattern
name|p
init|=
operator|new
name|ComparisonImpl
operator|.
name|LikePattern
argument_list|(
name|pattern
argument_list|)
decl_stmt|;
if|if
condition|(
name|match
operator|!=
literal|null
condition|)
block|{
name|assertTrue
argument_list|(
name|p
operator|.
name|matches
argument_list|(
name|match
argument_list|)
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|noMatch
operator|!=
literal|null
condition|)
block|{
name|assertFalse
argument_list|(
name|p
operator|.
name|matches
argument_list|(
name|noMatch
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|assertEquals
argument_list|(
name|lower
argument_list|,
name|p
operator|.
name|getLowerBound
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|upper
argument_list|,
name|p
operator|.
name|getUpperBound
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

