begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|index
operator|.
name|solr
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Nonnull
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|index
operator|.
name|IndexHookProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|index
operator|.
name|solr
operator|.
name|index
operator|.
name|SolrIndexHookProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|index
operator|.
name|solr
operator|.
name|query
operator|.
name|SolrQueryIndexProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|query
operator|.
name|QueryIndexProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|client
operator|.
name|solrj
operator|.
name|SolrServer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|client
operator|.
name|solrj
operator|.
name|SolrServerException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|BundleContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|BundleReference
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|ServiceReference
import|;
end_import

begin_comment
comment|/**  * Utilities for Oak Solr integration.  */
end_comment

begin_class
specifier|public
class|class
name|OakSolrUtils
block|{
comment|/**      * Check if a given Solr instance is alive      *      * @param solrServer the {@link SolrServer} used to communicate with the Solr instance      * @return<code>true</code> if the given Solr instance is alive and responding      * @throws IOException         if any low level IO error occurs      * @throws SolrServerException if any error occurs while trying to communicate with the Solr instance      */
specifier|public
specifier|static
name|boolean
name|checkServerAlive
parameter_list|(
annotation|@
name|Nonnull
name|SolrServer
name|solrServer
parameter_list|)
throws|throws
name|IOException
throws|,
name|SolrServerException
block|{
return|return
name|solrServer
operator|.
name|ping
argument_list|()
operator|.
name|getStatus
argument_list|()
operator|==
literal|0
return|;
block|}
comment|/**      * adapts the OSGi Solr {@link IndexHookProvider} service      *      * @return a {@link SolrIndexHookProvider}      */
specifier|public
specifier|static
name|IndexHookProvider
name|adaptOsgiIndexHookProvider
parameter_list|()
block|{
name|BundleContext
name|ctx
init|=
name|BundleReference
operator|.
name|class
operator|.
name|cast
argument_list|(
name|SolrIndexHookProvider
operator|.
name|class
operator|.
name|getClassLoader
argument_list|()
argument_list|)
operator|.
name|getBundle
argument_list|()
operator|.
name|getBundleContext
argument_list|()
decl_stmt|;
name|ServiceReference
name|serviceReference
init|=
name|ctx
operator|.
name|getServiceReference
argument_list|(
name|SolrIndexHookProvider
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|)
decl_stmt|;
return|return
name|SolrIndexHookProvider
operator|.
name|class
operator|.
name|cast
argument_list|(
name|ctx
operator|.
name|getService
argument_list|(
name|serviceReference
argument_list|)
argument_list|)
return|;
block|}
comment|/**      * adapts the OSGi Solr {@link QueryIndexProvider} service      *      * @return a {@link SolrQueryIndexProvider}      */
specifier|public
specifier|static
name|QueryIndexProvider
name|adaptOsgiQueryIndexProvider
parameter_list|()
block|{
name|BundleContext
name|ctx
init|=
name|BundleReference
operator|.
name|class
operator|.
name|cast
argument_list|(
name|SolrQueryIndexProvider
operator|.
name|class
operator|.
name|getClassLoader
argument_list|()
argument_list|)
operator|.
name|getBundle
argument_list|()
operator|.
name|getBundleContext
argument_list|()
decl_stmt|;
name|ServiceReference
name|serviceReference
init|=
name|ctx
operator|.
name|getServiceReference
argument_list|(
name|SolrQueryIndexProvider
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|)
decl_stmt|;
return|return
name|SolrQueryIndexProvider
operator|.
name|class
operator|.
name|cast
argument_list|(
name|ctx
operator|.
name|getService
argument_list|(
name|serviceReference
argument_list|)
argument_list|)
return|;
block|}
comment|/**      * Trigger a Solr commit on the basis of the given commit policy (e.g. hard, soft, auto)      *      * @param solrServer   the {@link SolrServer} used to communicate with the Solr instance      * @param commitPolicy the {@link CommitPolicy} used to commit changes to a Solr index      * @throws IOException         if any low level IO error occurs      * @throws SolrServerException if any error occurs while trying to communicate with the Solr instance      */
specifier|public
specifier|static
name|void
name|commitByPolicy
parameter_list|(
name|SolrServer
name|solrServer
parameter_list|,
name|CommitPolicy
name|commitPolicy
parameter_list|)
throws|throws
name|IOException
throws|,
name|SolrServerException
block|{
switch|switch
condition|(
name|commitPolicy
condition|)
block|{
case|case
name|HARD
case|:
block|{
name|solrServer
operator|.
name|commit
argument_list|()
expr_stmt|;
break|break;
block|}
case|case
name|SOFT
case|:
block|{
name|solrServer
operator|.
name|commit
argument_list|(
literal|false
argument_list|,
literal|false
argument_list|,
literal|true
argument_list|)
expr_stmt|;
break|break;
block|}
case|case
name|AUTO
case|:
block|{
break|break;
block|}
block|}
block|}
block|}
end_class

end_unit

