begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|memory
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|PropertyState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|Type
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|value
operator|.
name|Conversions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|value
operator|.
name|Conversions
operator|.
name|Converter
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|Type
operator|.
name|BOOLEANS
import|;
end_import

begin_class
specifier|public
class|class
name|MultiBooleanPropertyState
extends|extends
name|MultiPropertyState
argument_list|<
name|Boolean
argument_list|>
block|{
specifier|public
name|MultiBooleanPropertyState
parameter_list|(
name|String
name|name
parameter_list|,
name|Iterable
argument_list|<
name|Boolean
argument_list|>
name|values
parameter_list|)
block|{
name|super
argument_list|(
name|name
argument_list|,
name|values
argument_list|)
expr_stmt|;
block|}
comment|/**      * Create a multi valued {@code PropertyState} from a list of booleans.      * @param name  The name of the property state      * @param values  The values of the property state      * @return  The new property state of type {@link Type#BOOLEANS}      */
specifier|public
specifier|static
name|PropertyState
name|booleanProperty
parameter_list|(
name|String
name|name
parameter_list|,
name|Iterable
argument_list|<
name|Boolean
argument_list|>
name|values
parameter_list|)
block|{
return|return
operator|new
name|MultiBooleanPropertyState
argument_list|(
name|name
argument_list|,
name|values
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|Converter
name|getConverter
parameter_list|(
name|Boolean
name|value
parameter_list|)
block|{
return|return
name|Conversions
operator|.
name|convert
argument_list|(
name|value
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|Type
argument_list|<
name|?
argument_list|>
name|getType
parameter_list|()
block|{
return|return
name|BOOLEANS
return|;
block|}
block|}
end_class

end_unit

