begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|document
operator|.
name|mongo
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|atomic
operator|.
name|AtomicReference
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|ReadConcern
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|ReadPreference
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|WriteConcern
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|client
operator|.
name|ListCollectionsIterable
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|client
operator|.
name|MongoCollection
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|client
operator|.
name|MongoDatabase
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|client
operator|.
name|MongoIterable
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|client
operator|.
name|model
operator|.
name|CreateCollectionOptions
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|client
operator|.
name|model
operator|.
name|CreateViewOptions
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|session
operator|.
name|ClientSession
import|;
end_import

begin_import
import|import
name|org
operator|.
name|bson
operator|.
name|Document
import|;
end_import

begin_import
import|import
name|org
operator|.
name|bson
operator|.
name|codecs
operator|.
name|configuration
operator|.
name|CodecRegistry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|bson
operator|.
name|conversions
operator|.
name|Bson
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jetbrains
operator|.
name|annotations
operator|.
name|NotNull
import|;
end_import

begin_class
class|class
name|MongoTestDatabase
implements|implements
name|MongoDatabase
block|{
specifier|private
specifier|final
name|MongoDatabase
name|db
decl_stmt|;
specifier|private
specifier|final
name|AtomicReference
argument_list|<
name|String
argument_list|>
name|beforeQueryException
decl_stmt|;
specifier|private
specifier|final
name|AtomicReference
argument_list|<
name|String
argument_list|>
name|beforeUpdateException
decl_stmt|;
specifier|private
specifier|final
name|AtomicReference
argument_list|<
name|String
argument_list|>
name|afterUpdateException
decl_stmt|;
name|MongoTestDatabase
parameter_list|(
name|MongoDatabase
name|db
parameter_list|,
name|AtomicReference
argument_list|<
name|String
argument_list|>
name|beforeQueryException
parameter_list|,
name|AtomicReference
argument_list|<
name|String
argument_list|>
name|beforeUpdateException
parameter_list|,
name|AtomicReference
argument_list|<
name|String
argument_list|>
name|afterUpdateException
parameter_list|)
block|{
name|this
operator|.
name|db
operator|=
name|db
expr_stmt|;
name|this
operator|.
name|beforeQueryException
operator|=
name|beforeQueryException
expr_stmt|;
name|this
operator|.
name|beforeUpdateException
operator|=
name|beforeUpdateException
expr_stmt|;
name|this
operator|.
name|afterUpdateException
operator|=
name|afterUpdateException
expr_stmt|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
name|db
operator|.
name|getName
argument_list|()
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|CodecRegistry
name|getCodecRegistry
parameter_list|()
block|{
return|return
name|db
operator|.
name|getCodecRegistry
argument_list|()
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|ReadPreference
name|getReadPreference
parameter_list|()
block|{
return|return
name|db
operator|.
name|getReadPreference
argument_list|()
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|WriteConcern
name|getWriteConcern
parameter_list|()
block|{
return|return
name|db
operator|.
name|getWriteConcern
argument_list|()
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|ReadConcern
name|getReadConcern
parameter_list|()
block|{
return|return
name|db
operator|.
name|getReadConcern
argument_list|()
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|MongoDatabase
name|withCodecRegistry
parameter_list|(
annotation|@
name|NotNull
name|CodecRegistry
name|codecRegistry
parameter_list|)
block|{
return|return
operator|new
name|MongoTestDatabase
argument_list|(
name|db
operator|.
name|withCodecRegistry
argument_list|(
name|codecRegistry
argument_list|)
argument_list|,
name|beforeQueryException
argument_list|,
name|beforeUpdateException
argument_list|,
name|afterUpdateException
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|MongoDatabase
name|withReadPreference
parameter_list|(
annotation|@
name|NotNull
name|ReadPreference
name|readPreference
parameter_list|)
block|{
return|return
operator|new
name|MongoTestDatabase
argument_list|(
name|db
operator|.
name|withReadPreference
argument_list|(
name|readPreference
argument_list|)
argument_list|,
name|beforeQueryException
argument_list|,
name|beforeUpdateException
argument_list|,
name|afterUpdateException
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|MongoDatabase
name|withWriteConcern
parameter_list|(
annotation|@
name|NotNull
name|WriteConcern
name|writeConcern
parameter_list|)
block|{
return|return
operator|new
name|MongoTestDatabase
argument_list|(
name|db
operator|.
name|withWriteConcern
argument_list|(
name|writeConcern
argument_list|)
argument_list|,
name|beforeQueryException
argument_list|,
name|beforeUpdateException
argument_list|,
name|afterUpdateException
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|MongoDatabase
name|withReadConcern
parameter_list|(
annotation|@
name|NotNull
name|ReadConcern
name|readConcern
parameter_list|)
block|{
return|return
operator|new
name|MongoTestDatabase
argument_list|(
name|db
operator|.
name|withReadConcern
argument_list|(
name|readConcern
argument_list|)
argument_list|,
name|beforeQueryException
argument_list|,
name|beforeUpdateException
argument_list|,
name|afterUpdateException
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|MongoCollection
argument_list|<
name|Document
argument_list|>
name|getCollection
parameter_list|(
annotation|@
name|NotNull
name|String
name|collectionName
parameter_list|)
block|{
return|return
operator|new
name|MongoTestCollection
argument_list|<>
argument_list|(
name|db
operator|.
name|getCollection
argument_list|(
name|collectionName
argument_list|)
argument_list|,
name|beforeQueryException
argument_list|,
name|beforeUpdateException
argument_list|,
name|afterUpdateException
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
parameter_list|<
name|TDocument
parameter_list|>
name|MongoCollection
argument_list|<
name|TDocument
argument_list|>
name|getCollection
parameter_list|(
annotation|@
name|NotNull
name|String
name|collectionName
parameter_list|,
annotation|@
name|NotNull
name|Class
argument_list|<
name|TDocument
argument_list|>
name|tDocumentClass
parameter_list|)
block|{
return|return
operator|new
name|MongoTestCollection
argument_list|<>
argument_list|(
name|db
operator|.
name|getCollection
argument_list|(
name|collectionName
argument_list|,
name|tDocumentClass
argument_list|)
argument_list|,
name|beforeQueryException
argument_list|,
name|beforeUpdateException
argument_list|,
name|afterUpdateException
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|Document
name|runCommand
parameter_list|(
annotation|@
name|NotNull
name|Bson
name|command
parameter_list|)
block|{
return|return
name|db
operator|.
name|runCommand
argument_list|(
name|command
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|Document
name|runCommand
parameter_list|(
annotation|@
name|NotNull
name|Bson
name|command
parameter_list|,
annotation|@
name|NotNull
name|ReadPreference
name|readPreference
parameter_list|)
block|{
return|return
name|db
operator|.
name|runCommand
argument_list|(
name|command
argument_list|,
name|readPreference
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
parameter_list|<
name|TResult
parameter_list|>
name|TResult
name|runCommand
parameter_list|(
annotation|@
name|NotNull
name|Bson
name|command
parameter_list|,
annotation|@
name|NotNull
name|Class
argument_list|<
name|TResult
argument_list|>
name|tResultClass
parameter_list|)
block|{
return|return
name|db
operator|.
name|runCommand
argument_list|(
name|command
argument_list|,
name|tResultClass
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
parameter_list|<
name|TResult
parameter_list|>
name|TResult
name|runCommand
parameter_list|(
annotation|@
name|NotNull
name|Bson
name|command
parameter_list|,
annotation|@
name|NotNull
name|ReadPreference
name|readPreference
parameter_list|,
annotation|@
name|NotNull
name|Class
argument_list|<
name|TResult
argument_list|>
name|tResultClass
parameter_list|)
block|{
return|return
name|db
operator|.
name|runCommand
argument_list|(
name|command
argument_list|,
name|readPreference
argument_list|,
name|tResultClass
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|Document
name|runCommand
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|Bson
name|command
parameter_list|)
block|{
return|return
name|db
operator|.
name|runCommand
argument_list|(
name|clientSession
argument_list|,
name|command
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|Document
name|runCommand
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|Bson
name|command
parameter_list|,
annotation|@
name|NotNull
name|ReadPreference
name|readPreference
parameter_list|)
block|{
return|return
name|db
operator|.
name|runCommand
argument_list|(
name|clientSession
argument_list|,
name|command
argument_list|,
name|readPreference
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
parameter_list|<
name|TResult
parameter_list|>
name|TResult
name|runCommand
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|Bson
name|command
parameter_list|,
annotation|@
name|NotNull
name|Class
argument_list|<
name|TResult
argument_list|>
name|tResultClass
parameter_list|)
block|{
return|return
name|db
operator|.
name|runCommand
argument_list|(
name|clientSession
argument_list|,
name|command
argument_list|,
name|tResultClass
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
parameter_list|<
name|TResult
parameter_list|>
name|TResult
name|runCommand
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|Bson
name|command
parameter_list|,
annotation|@
name|NotNull
name|ReadPreference
name|readPreference
parameter_list|,
annotation|@
name|NotNull
name|Class
argument_list|<
name|TResult
argument_list|>
name|tResultClass
parameter_list|)
block|{
return|return
name|db
operator|.
name|runCommand
argument_list|(
name|clientSession
argument_list|,
name|command
argument_list|,
name|readPreference
argument_list|,
name|tResultClass
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|drop
parameter_list|()
block|{
name|db
operator|.
name|drop
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|drop
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|)
block|{
name|db
operator|.
name|drop
argument_list|(
name|clientSession
argument_list|)
expr_stmt|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|MongoIterable
argument_list|<
name|String
argument_list|>
name|listCollectionNames
parameter_list|()
block|{
return|return
name|db
operator|.
name|listCollectionNames
argument_list|()
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|ListCollectionsIterable
argument_list|<
name|Document
argument_list|>
name|listCollections
parameter_list|()
block|{
return|return
name|db
operator|.
name|listCollections
argument_list|()
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
parameter_list|<
name|TResult
parameter_list|>
name|ListCollectionsIterable
argument_list|<
name|TResult
argument_list|>
name|listCollections
parameter_list|(
annotation|@
name|NotNull
name|Class
argument_list|<
name|TResult
argument_list|>
name|tResultClass
parameter_list|)
block|{
return|return
name|db
operator|.
name|listCollections
argument_list|(
name|tResultClass
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|MongoIterable
argument_list|<
name|String
argument_list|>
name|listCollectionNames
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|)
block|{
return|return
name|db
operator|.
name|listCollectionNames
argument_list|(
name|clientSession
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
name|ListCollectionsIterable
argument_list|<
name|Document
argument_list|>
name|listCollections
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|)
block|{
return|return
name|db
operator|.
name|listCollections
argument_list|(
name|clientSession
argument_list|)
return|;
block|}
annotation|@
name|NotNull
annotation|@
name|Override
specifier|public
parameter_list|<
name|TResult
parameter_list|>
name|ListCollectionsIterable
argument_list|<
name|TResult
argument_list|>
name|listCollections
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|Class
argument_list|<
name|TResult
argument_list|>
name|tResultClass
parameter_list|)
block|{
return|return
name|db
operator|.
name|listCollections
argument_list|(
name|clientSession
argument_list|,
name|tResultClass
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|createCollection
parameter_list|(
annotation|@
name|NotNull
name|String
name|collectionName
parameter_list|)
block|{
name|db
operator|.
name|createCollection
argument_list|(
name|collectionName
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|createCollection
parameter_list|(
annotation|@
name|NotNull
name|String
name|collectionName
parameter_list|,
annotation|@
name|NotNull
name|CreateCollectionOptions
name|createCollectionOptions
parameter_list|)
block|{
name|db
operator|.
name|createCollection
argument_list|(
name|collectionName
argument_list|,
name|createCollectionOptions
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|createCollection
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|String
name|collectionName
parameter_list|)
block|{
name|db
operator|.
name|createCollection
argument_list|(
name|clientSession
argument_list|,
name|collectionName
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|createCollection
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|String
name|collectionName
parameter_list|,
annotation|@
name|NotNull
name|CreateCollectionOptions
name|createCollectionOptions
parameter_list|)
block|{
name|db
operator|.
name|createCollection
argument_list|(
name|clientSession
argument_list|,
name|collectionName
argument_list|,
name|createCollectionOptions
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|createView
parameter_list|(
annotation|@
name|NotNull
name|String
name|viewName
parameter_list|,
annotation|@
name|NotNull
name|String
name|viewOn
parameter_list|,
annotation|@
name|NotNull
name|List
argument_list|<
name|?
extends|extends
name|Bson
argument_list|>
name|pipeline
parameter_list|)
block|{
name|db
operator|.
name|createView
argument_list|(
name|viewName
argument_list|,
name|viewOn
argument_list|,
name|pipeline
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|createView
parameter_list|(
annotation|@
name|NotNull
name|String
name|viewName
parameter_list|,
annotation|@
name|NotNull
name|String
name|viewOn
parameter_list|,
annotation|@
name|NotNull
name|List
argument_list|<
name|?
extends|extends
name|Bson
argument_list|>
name|pipeline
parameter_list|,
annotation|@
name|NotNull
name|CreateViewOptions
name|createViewOptions
parameter_list|)
block|{
name|db
operator|.
name|createView
argument_list|(
name|viewName
argument_list|,
name|viewOn
argument_list|,
name|pipeline
argument_list|,
name|createViewOptions
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|createView
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|String
name|viewName
parameter_list|,
annotation|@
name|NotNull
name|String
name|viewOn
parameter_list|,
annotation|@
name|NotNull
name|List
argument_list|<
name|?
extends|extends
name|Bson
argument_list|>
name|pipeline
parameter_list|)
block|{
name|db
operator|.
name|createView
argument_list|(
name|clientSession
argument_list|,
name|viewName
argument_list|,
name|viewOn
argument_list|,
name|pipeline
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|createView
parameter_list|(
annotation|@
name|NotNull
name|ClientSession
name|clientSession
parameter_list|,
annotation|@
name|NotNull
name|String
name|viewName
parameter_list|,
annotation|@
name|NotNull
name|String
name|viewOn
parameter_list|,
annotation|@
name|NotNull
name|List
argument_list|<
name|?
extends|extends
name|Bson
argument_list|>
name|pipeline
parameter_list|,
annotation|@
name|NotNull
name|CreateViewOptions
name|createViewOptions
parameter_list|)
block|{
name|db
operator|.
name|createView
argument_list|(
name|clientSession
argument_list|,
name|viewName
argument_list|,
name|viewOn
argument_list|,
name|pipeline
argument_list|,
name|createViewOptions
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

