begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|observation
package|;
end_package

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Preconditions
operator|.
name|checkNotNull
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Nonnull
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|commit
operator|.
name|DefaultEditor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|commit
operator|.
name|Editor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|commit
operator|.
name|EditorProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|state
operator|.
name|NodeBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|state
operator|.
name|NodeState
import|;
end_import

begin_comment
comment|/**  * Provider for a {@link Editor} that amends each commit with  * a commit info record. That record is stored in a child node  * named {@link #COMMIT_INFO} of the root node.  */
end_comment

begin_class
specifier|public
class|class
name|CommitInfoEditorProvider
implements|implements
name|EditorProvider
block|{
comment|/**      * Node name for the commit info record      */
specifier|public
specifier|static
specifier|final
name|String
name|COMMIT_INFO
init|=
literal|":commit-info"
decl_stmt|;
comment|/**      * Name of the property containing the id of the session that committed      * this revision.      *<p>      * In a clustered environment this property might contain a synthesised      * value if the respective revision is the result of a cluster sync.      */
specifier|public
specifier|static
specifier|final
name|String
name|SESSION_ID
init|=
literal|"session-id"
decl_stmt|;
comment|/**      * Name of the property containing the id of the user that committed      * this revision.      *<p>      * In a clustered environment this property might contain a synthesised      * value if the respective revision is the result of a cluster sync.      */
specifier|public
specifier|static
specifier|final
name|String
name|USER_ID
init|=
literal|"user-id"
decl_stmt|;
comment|/**      * Name of the property containing the time stamp when this revision was      * committed.      */
specifier|public
specifier|static
specifier|final
name|String
name|TIME_STAMP
init|=
literal|"time-stamp"
decl_stmt|;
specifier|private
specifier|final
name|String
name|sessionId
decl_stmt|;
specifier|private
specifier|final
name|String
name|userId
decl_stmt|;
specifier|public
name|CommitInfoEditorProvider
parameter_list|(
annotation|@
name|Nonnull
name|String
name|sessionId
parameter_list|,
name|String
name|userID
parameter_list|)
block|{
name|this
operator|.
name|sessionId
operator|=
name|checkNotNull
argument_list|(
name|sessionId
argument_list|)
expr_stmt|;
name|this
operator|.
name|userId
operator|=
name|userID
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|Editor
name|getRootEditor
parameter_list|(
name|NodeState
name|before
parameter_list|,
name|NodeState
name|after
parameter_list|,
specifier|final
name|NodeBuilder
name|builder
parameter_list|)
block|{
return|return
operator|new
name|DefaultEditor
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|enter
parameter_list|(
name|NodeState
name|before
parameter_list|,
name|NodeState
name|after
parameter_list|)
block|{
name|NodeBuilder
name|commitInfo
init|=
name|builder
operator|.
name|setChildNode
argument_list|(
name|COMMIT_INFO
argument_list|)
decl_stmt|;
name|commitInfo
operator|.
name|setProperty
argument_list|(
name|USER_ID
argument_list|,
name|String
operator|.
name|valueOf
argument_list|(
name|userId
argument_list|)
argument_list|)
expr_stmt|;
name|commitInfo
operator|.
name|setProperty
argument_list|(
name|SESSION_ID
argument_list|,
name|sessionId
argument_list|)
expr_stmt|;
name|commitInfo
operator|.
name|setProperty
argument_list|(
name|TIME_STAMP
argument_list|,
name|System
operator|.
name|currentTimeMillis
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
return|;
block|}
block|}
end_class

end_unit

