begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|security
operator|.
name|authorization
operator|.
name|composite
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|LinkedHashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Nonnull
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Nullable
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableMap
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|PropertyState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|Root
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|Tree
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|tree
operator|.
name|RootFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|tree
operator|.
name|TreeLocation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|tree
operator|.
name|impl
operator|.
name|ImmutableTree
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|security
operator|.
name|authorization
operator|.
name|permission
operator|.
name|PermissionUtil
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|Context
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|authorization
operator|.
name|permission
operator|.
name|AggregatedPermissionProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|authorization
operator|.
name|permission
operator|.
name|PermissionProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|authorization
operator|.
name|permission
operator|.
name|Permissions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|authorization
operator|.
name|permission
operator|.
name|RepositoryPermission
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|authorization
operator|.
name|permission
operator|.
name|TreePermission
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|privilege
operator|.
name|PrivilegeBits
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|privilege
operator|.
name|PrivilegeBitsProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|state
operator|.
name|NodeState
import|;
end_import

begin_comment
comment|/**  * Permission provider implementation that aggregates a list of different  * provider implementations. Note, that the implementations *must* implement  * the {@link org.apache.jackrabbit.oak.spi.security.authorization.permission.AggregatedPermissionProvider}  * interface.  *  * TODO This is work in progress (OAK-1268)  */
end_comment

begin_class
class|class
name|CompositePermissionProvider
implements|implements
name|PermissionProvider
block|{
specifier|private
specifier|final
name|Root
name|root
decl_stmt|;
specifier|private
specifier|final
name|List
argument_list|<
name|AggregatedPermissionProvider
argument_list|>
name|pps
decl_stmt|;
specifier|private
specifier|final
name|Context
name|ctx
decl_stmt|;
specifier|private
specifier|final
name|CompositeRepositoryPermission
name|repositoryPermission
decl_stmt|;
specifier|private
name|Root
name|immutableRoot
decl_stmt|;
specifier|private
name|PrivilegeBitsProvider
name|privilegeBitsProvider
decl_stmt|;
name|CompositePermissionProvider
parameter_list|(
annotation|@
name|Nonnull
name|Root
name|root
parameter_list|,
annotation|@
name|Nonnull
name|List
argument_list|<
name|AggregatedPermissionProvider
argument_list|>
name|pps
parameter_list|,
annotation|@
name|Nonnull
name|Context
name|acContext
parameter_list|)
block|{
name|this
operator|.
name|root
operator|=
name|root
expr_stmt|;
name|this
operator|.
name|pps
operator|=
name|pps
expr_stmt|;
name|this
operator|.
name|ctx
operator|=
name|acContext
expr_stmt|;
name|repositoryPermission
operator|=
operator|new
name|CompositeRepositoryPermission
argument_list|()
expr_stmt|;
name|immutableRoot
operator|=
name|RootFactory
operator|.
name|createReadOnlyRoot
argument_list|(
name|root
argument_list|)
expr_stmt|;
name|privilegeBitsProvider
operator|=
operator|new
name|PrivilegeBitsProvider
argument_list|(
name|immutableRoot
argument_list|)
expr_stmt|;
block|}
comment|//-------------------------------------------------< PermissionProvider>---
annotation|@
name|Override
specifier|public
name|void
name|refresh
parameter_list|()
block|{
name|immutableRoot
operator|=
name|RootFactory
operator|.
name|createReadOnlyRoot
argument_list|(
name|root
argument_list|)
expr_stmt|;
name|privilegeBitsProvider
operator|=
operator|new
name|PrivilegeBitsProvider
argument_list|(
name|immutableRoot
argument_list|)
expr_stmt|;
for|for
control|(
name|PermissionProvider
name|pp
range|:
name|pps
control|)
block|{
name|pp
operator|.
name|refresh
argument_list|()
expr_stmt|;
block|}
block|}
annotation|@
name|Nonnull
annotation|@
name|Override
specifier|public
name|Set
argument_list|<
name|String
argument_list|>
name|getPrivileges
parameter_list|(
annotation|@
name|Nullable
name|Tree
name|tree
parameter_list|)
block|{
name|Tree
name|immutableTree
init|=
name|PermissionUtil
operator|.
name|getImmutableTree
argument_list|(
name|tree
argument_list|,
name|immutableRoot
argument_list|)
decl_stmt|;
name|PrivilegeBits
name|result
init|=
name|PrivilegeBits
operator|.
name|getInstance
argument_list|()
decl_stmt|;
name|PrivilegeBits
name|denied
init|=
name|PrivilegeBits
operator|.
name|getInstance
argument_list|()
decl_stmt|;
for|for
control|(
name|AggregatedPermissionProvider
name|aggregatedPermissionProvider
range|:
name|pps
control|)
block|{
name|PrivilegeBits
name|supported
init|=
name|aggregatedPermissionProvider
operator|.
name|supportedPrivileges
argument_list|(
name|immutableTree
argument_list|,
literal|null
argument_list|)
operator|.
name|modifiable
argument_list|()
decl_stmt|;
if|if
condition|(
name|doEvaluate
argument_list|(
name|supported
argument_list|)
condition|)
block|{
name|PrivilegeBits
name|granted
init|=
name|privilegeBitsProvider
operator|.
name|getBits
argument_list|(
name|aggregatedPermissionProvider
operator|.
name|getPrivileges
argument_list|(
name|immutableTree
argument_list|)
argument_list|)
decl_stmt|;
comment|// make sure privs denied by a previous provider are substracted
if|if
condition|(
operator|!
name|denied
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|result
operator|.
name|add
argument_list|(
name|granted
operator|.
name|modifiable
argument_list|()
operator|.
name|diff
argument_list|(
name|denied
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|result
operator|.
name|add
argument_list|(
name|granted
argument_list|)
expr_stmt|;
block|}
comment|// update the set of denied privs by comparing the granted privs
comment|// the complete set of supported privileges.
name|denied
operator|.
name|add
argument_list|(
name|supported
operator|.
name|diff
argument_list|(
name|granted
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|privilegeBitsProvider
operator|.
name|getPrivilegeNames
argument_list|(
name|result
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|hasPrivileges
parameter_list|(
annotation|@
name|Nullable
name|Tree
name|tree
parameter_list|,
annotation|@
name|Nonnull
name|String
modifier|...
name|privilegeNames
parameter_list|)
block|{
name|Tree
name|immutableTree
init|=
name|PermissionUtil
operator|.
name|getImmutableTree
argument_list|(
name|tree
argument_list|,
name|immutableRoot
argument_list|)
decl_stmt|;
name|PrivilegeBits
name|privilegeBits
init|=
name|privilegeBitsProvider
operator|.
name|getBits
argument_list|(
name|privilegeNames
argument_list|)
decl_stmt|;
name|boolean
name|hasPrivileges
init|=
literal|false
decl_stmt|;
name|PrivilegeBits
name|coveredPrivs
init|=
name|PrivilegeBits
operator|.
name|getInstance
argument_list|()
decl_stmt|;
for|for
control|(
name|AggregatedPermissionProvider
name|aggregatedPermissionProvider
range|:
name|pps
control|)
block|{
name|PrivilegeBits
name|supported
init|=
name|aggregatedPermissionProvider
operator|.
name|supportedPrivileges
argument_list|(
name|immutableTree
argument_list|,
name|privilegeBits
argument_list|)
decl_stmt|;
if|if
condition|(
name|doEvaluate
argument_list|(
name|supported
argument_list|)
condition|)
block|{
name|Set
argument_list|<
name|String
argument_list|>
name|supportedNames
init|=
name|privilegeBitsProvider
operator|.
name|getPrivilegeNames
argument_list|(
name|supported
argument_list|)
decl_stmt|;
name|hasPrivileges
operator|=
name|aggregatedPermissionProvider
operator|.
name|hasPrivileges
argument_list|(
name|immutableTree
argument_list|,
name|supportedNames
operator|.
name|toArray
argument_list|(
operator|new
name|String
index|[
name|supportedNames
operator|.
name|size
argument_list|()
index|]
argument_list|)
argument_list|)
expr_stmt|;
name|coveredPrivs
operator|.
name|add
argument_list|(
name|supported
argument_list|)
expr_stmt|;
empty_stmt|;
if|if
condition|(
operator|!
name|hasPrivileges
condition|)
block|{
break|break;
block|}
block|}
block|}
return|return
name|hasPrivileges
operator|&&
name|coveredPrivs
operator|.
name|includes
argument_list|(
name|privilegeBits
argument_list|)
return|;
block|}
annotation|@
name|Nonnull
annotation|@
name|Override
specifier|public
name|RepositoryPermission
name|getRepositoryPermission
parameter_list|()
block|{
return|return
name|repositoryPermission
return|;
block|}
annotation|@
name|Nonnull
annotation|@
name|Override
specifier|public
name|TreePermission
name|getTreePermission
parameter_list|(
annotation|@
name|Nonnull
name|Tree
name|tree
parameter_list|,
annotation|@
name|Nonnull
name|TreePermission
name|parentPermission
parameter_list|)
block|{
name|ImmutableTree
name|immutableTree
init|=
operator|(
name|ImmutableTree
operator|)
name|PermissionUtil
operator|.
name|getImmutableTree
argument_list|(
name|tree
argument_list|,
name|immutableRoot
argument_list|)
decl_stmt|;
if|if
condition|(
name|tree
operator|.
name|isRoot
argument_list|()
condition|)
block|{
return|return
operator|new
name|CompositeTreePermission
argument_list|(
name|immutableTree
argument_list|,
operator|new
name|CompositeTreePermission
argument_list|()
argument_list|)
return|;
block|}
else|else
block|{
if|if
condition|(
operator|!
operator|(
name|parentPermission
operator|instanceof
name|CompositeTreePermission
operator|)
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Illegal parent permission instance. Expected CompositeTreePermission."
argument_list|)
throw|;
block|}
return|return
operator|new
name|CompositeTreePermission
argument_list|(
name|immutableTree
argument_list|,
operator|(
name|CompositeTreePermission
operator|)
name|parentPermission
argument_list|)
return|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isGranted
parameter_list|(
annotation|@
name|Nonnull
name|Tree
name|parent
parameter_list|,
annotation|@
name|Nullable
name|PropertyState
name|property
parameter_list|,
name|long
name|permissions
parameter_list|)
block|{
name|Tree
name|immParent
init|=
name|PermissionUtil
operator|.
name|getImmutableTree
argument_list|(
name|parent
argument_list|,
name|immutableRoot
argument_list|)
decl_stmt|;
name|boolean
name|isGranted
init|=
literal|false
decl_stmt|;
name|long
name|coveredPermissions
init|=
name|Permissions
operator|.
name|NO_PERMISSION
decl_stmt|;
for|for
control|(
name|AggregatedPermissionProvider
name|aggregatedPermissionProvider
range|:
name|pps
control|)
block|{
name|long
name|supportedPermissions
init|=
name|aggregatedPermissionProvider
operator|.
name|supportedPermissions
argument_list|(
name|immParent
argument_list|,
name|property
argument_list|,
name|permissions
argument_list|)
decl_stmt|;
if|if
condition|(
name|doEvaluate
argument_list|(
name|supportedPermissions
argument_list|)
condition|)
block|{
name|isGranted
operator|=
name|aggregatedPermissionProvider
operator|.
name|isGranted
argument_list|(
name|immParent
argument_list|,
name|property
argument_list|,
name|supportedPermissions
argument_list|)
expr_stmt|;
name|coveredPermissions
operator||=
name|supportedPermissions
expr_stmt|;
if|if
condition|(
operator|!
name|isGranted
condition|)
block|{
break|break;
block|}
block|}
block|}
return|return
name|isGranted
operator|&&
name|coveredPermissions
operator|==
name|permissions
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isGranted
parameter_list|(
annotation|@
name|Nonnull
name|String
name|oakPath
parameter_list|,
annotation|@
name|Nonnull
name|String
name|jcrActions
parameter_list|)
block|{
name|TreeLocation
name|location
init|=
name|TreeLocation
operator|.
name|create
argument_list|(
name|immutableRoot
argument_list|,
name|oakPath
argument_list|)
decl_stmt|;
name|boolean
name|isAcContent
init|=
name|ctx
operator|.
name|definesLocation
argument_list|(
name|location
argument_list|)
decl_stmt|;
name|long
name|permissions
init|=
name|Permissions
operator|.
name|getPermissions
argument_list|(
name|jcrActions
argument_list|,
name|location
argument_list|,
name|isAcContent
argument_list|)
decl_stmt|;
name|PropertyState
name|property
init|=
name|location
operator|.
name|getProperty
argument_list|()
decl_stmt|;
name|Tree
name|tree
init|=
operator|(
name|property
operator|==
literal|null
operator|)
condition|?
name|location
operator|.
name|getTree
argument_list|()
else|:
name|location
operator|.
name|getParent
argument_list|()
operator|.
name|getTree
argument_list|()
decl_stmt|;
if|if
condition|(
name|tree
operator|!=
literal|null
condition|)
block|{
return|return
name|isGranted
argument_list|(
name|tree
argument_list|,
name|property
argument_list|,
name|permissions
argument_list|)
return|;
block|}
else|else
block|{
name|boolean
name|isGranted
init|=
literal|false
decl_stmt|;
name|long
name|coveredPermissions
init|=
name|Permissions
operator|.
name|NO_PERMISSION
decl_stmt|;
for|for
control|(
name|AggregatedPermissionProvider
name|aggregatedPermissionProvider
range|:
name|pps
control|)
block|{
name|long
name|supportedPermissions
init|=
name|aggregatedPermissionProvider
operator|.
name|supportedPermissions
argument_list|(
name|location
argument_list|,
name|permissions
argument_list|)
decl_stmt|;
if|if
condition|(
name|doEvaluate
argument_list|(
name|supportedPermissions
argument_list|)
condition|)
block|{
name|isGranted
operator|=
name|aggregatedPermissionProvider
operator|.
name|isGranted
argument_list|(
name|location
argument_list|,
name|supportedPermissions
argument_list|)
expr_stmt|;
name|coveredPermissions
operator||=
name|supportedPermissions
expr_stmt|;
if|if
condition|(
operator|!
name|isGranted
condition|)
block|{
break|break;
block|}
block|}
block|}
return|return
name|isGranted
operator|&&
name|coveredPermissions
operator|==
name|permissions
return|;
block|}
block|}
comment|//------------------------------------------------------------< private>---
specifier|private
specifier|static
name|boolean
name|doEvaluate
parameter_list|(
name|long
name|supportedPermissions
parameter_list|)
block|{
return|return
name|supportedPermissions
operator|!=
name|Permissions
operator|.
name|NO_PERMISSION
return|;
block|}
specifier|private
specifier|static
name|boolean
name|doEvaluate
parameter_list|(
name|PrivilegeBits
name|supportedPrivileges
parameter_list|)
block|{
return|return
operator|!
name|supportedPrivileges
operator|.
name|isEmpty
argument_list|()
return|;
block|}
comment|//-----------------------------------------------------< TreePermission>---
comment|/**      * {@code TreePermission} implementation that wraps multiple implementations.      */
specifier|private
specifier|final
class|class
name|CompositeTreePermission
implements|implements
name|TreePermission
block|{
specifier|private
specifier|final
name|ImmutableTree
name|tree
decl_stmt|;
specifier|private
specifier|final
name|CompositeTreePermission
name|parentPermission
decl_stmt|;
specifier|private
specifier|final
name|Map
argument_list|<
name|AggregatedPermissionProvider
argument_list|,
name|TreePermission
argument_list|>
name|map
decl_stmt|;
specifier|private
name|Boolean
name|canRead
decl_stmt|;
specifier|private
name|CompositeTreePermission
parameter_list|()
block|{
name|tree
operator|=
literal|null
expr_stmt|;
name|parentPermission
operator|=
literal|null
expr_stmt|;
name|map
operator|=
name|ImmutableMap
operator|.
name|of
argument_list|()
expr_stmt|;
block|}
specifier|private
name|CompositeTreePermission
parameter_list|(
annotation|@
name|Nonnull
specifier|final
name|ImmutableTree
name|tree
parameter_list|,
annotation|@
name|Nonnull
name|CompositeTreePermission
name|parentPermission
parameter_list|)
block|{
name|this
operator|.
name|tree
operator|=
name|tree
expr_stmt|;
name|this
operator|.
name|parentPermission
operator|=
name|parentPermission
expr_stmt|;
name|map
operator|=
operator|new
name|LinkedHashMap
argument_list|<
name|AggregatedPermissionProvider
argument_list|,
name|TreePermission
argument_list|>
argument_list|(
name|pps
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
for|for
control|(
name|AggregatedPermissionProvider
name|provider
range|:
name|pps
control|)
block|{
name|TreePermission
name|tp
init|=
name|provider
operator|.
name|getTreePermission
argument_list|(
name|tree
argument_list|,
name|getParentPermission
argument_list|(
name|provider
argument_list|)
argument_list|)
decl_stmt|;
name|map
operator|.
name|put
argument_list|(
name|provider
argument_list|,
name|tp
argument_list|)
expr_stmt|;
block|}
block|}
annotation|@
name|Nonnull
annotation|@
name|Override
specifier|public
name|TreePermission
name|getChildPermission
parameter_list|(
annotation|@
name|Nonnull
name|String
name|childName
parameter_list|,
annotation|@
name|Nonnull
name|NodeState
name|childState
parameter_list|)
block|{
name|ImmutableTree
name|childTree
init|=
operator|new
name|ImmutableTree
argument_list|(
name|tree
argument_list|,
name|childName
argument_list|,
name|childState
argument_list|)
decl_stmt|;
return|return
operator|new
name|CompositeTreePermission
argument_list|(
name|childTree
argument_list|,
name|this
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|canRead
parameter_list|()
block|{
if|if
condition|(
name|canRead
operator|==
literal|null
condition|)
block|{
name|boolean
name|readable
init|=
literal|false
decl_stmt|;
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|AggregatedPermissionProvider
argument_list|,
name|TreePermission
argument_list|>
name|entry
range|:
name|map
operator|.
name|entrySet
argument_list|()
control|)
block|{
name|TreePermission
name|tp
init|=
name|entry
operator|.
name|getValue
argument_list|()
decl_stmt|;
name|long
name|supported
init|=
name|entry
operator|.
name|getKey
argument_list|()
operator|.
name|supportedPermissions
argument_list|(
name|tp
argument_list|,
name|Permissions
operator|.
name|READ_NODE
argument_list|)
decl_stmt|;
if|if
condition|(
name|doEvaluate
argument_list|(
name|supported
argument_list|)
condition|)
block|{
name|readable
operator|=
name|tp
operator|.
name|canRead
argument_list|()
expr_stmt|;
if|if
condition|(
operator|!
name|readable
condition|)
block|{
break|break;
block|}
block|}
block|}
name|canRead
operator|=
name|readable
expr_stmt|;
block|}
return|return
name|canRead
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|canRead
parameter_list|(
annotation|@
name|Nonnull
name|PropertyState
name|property
parameter_list|)
block|{
name|boolean
name|canReadProperty
init|=
literal|false
decl_stmt|;
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|AggregatedPermissionProvider
argument_list|,
name|TreePermission
argument_list|>
name|entry
range|:
name|map
operator|.
name|entrySet
argument_list|()
control|)
block|{
name|TreePermission
name|tp
init|=
name|entry
operator|.
name|getValue
argument_list|()
decl_stmt|;
name|long
name|supported
init|=
name|entry
operator|.
name|getKey
argument_list|()
operator|.
name|supportedPermissions
argument_list|(
name|tp
argument_list|,
name|Permissions
operator|.
name|READ_PROPERTY
argument_list|)
decl_stmt|;
if|if
condition|(
name|doEvaluate
argument_list|(
name|supported
argument_list|)
condition|)
block|{
name|canReadProperty
operator|=
name|tp
operator|.
name|canRead
argument_list|(
name|property
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|canReadProperty
condition|)
block|{
break|break;
block|}
block|}
block|}
return|return
name|canReadProperty
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|canReadAll
parameter_list|()
block|{
return|return
literal|false
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|canReadProperties
parameter_list|()
block|{
return|return
literal|false
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isGranted
parameter_list|(
name|long
name|permissions
parameter_list|)
block|{
return|return
name|grantsPermission
argument_list|(
name|permissions
argument_list|,
literal|null
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isGranted
parameter_list|(
name|long
name|permissions
parameter_list|,
annotation|@
name|Nonnull
name|PropertyState
name|property
parameter_list|)
block|{
return|return
name|grantsPermission
argument_list|(
name|permissions
argument_list|,
name|property
argument_list|)
return|;
block|}
specifier|private
name|boolean
name|grantsPermission
parameter_list|(
name|long
name|permissions
parameter_list|,
annotation|@
name|Nullable
name|PropertyState
name|property
parameter_list|)
block|{
name|boolean
name|isGranted
init|=
literal|false
decl_stmt|;
name|long
name|coveredPermissions
init|=
name|Permissions
operator|.
name|NO_PERMISSION
decl_stmt|;
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|AggregatedPermissionProvider
argument_list|,
name|TreePermission
argument_list|>
name|entry
range|:
name|map
operator|.
name|entrySet
argument_list|()
control|)
block|{
name|long
name|supportedPermissions
init|=
name|entry
operator|.
name|getKey
argument_list|()
operator|.
name|supportedPermissions
argument_list|(
name|tree
argument_list|,
name|property
argument_list|,
name|permissions
argument_list|)
decl_stmt|;
if|if
condition|(
name|doEvaluate
argument_list|(
name|supportedPermissions
argument_list|)
condition|)
block|{
name|TreePermission
name|tp
init|=
name|entry
operator|.
name|getValue
argument_list|()
decl_stmt|;
name|isGranted
operator|=
operator|(
name|property
operator|==
literal|null
operator|)
condition|?
name|tp
operator|.
name|isGranted
argument_list|(
name|supportedPermissions
argument_list|)
else|:
name|tp
operator|.
name|isGranted
argument_list|(
name|supportedPermissions
argument_list|,
name|property
argument_list|)
expr_stmt|;
name|coveredPermissions
operator||=
name|supportedPermissions
expr_stmt|;
if|if
condition|(
operator|!
name|isGranted
condition|)
block|{
return|return
literal|false
return|;
block|}
block|}
block|}
return|return
name|isGranted
operator|&&
name|coveredPermissions
operator|==
name|permissions
return|;
block|}
annotation|@
name|Nonnull
specifier|private
name|TreePermission
name|getParentPermission
parameter_list|(
name|AggregatedPermissionProvider
name|provider
parameter_list|)
block|{
name|TreePermission
name|parent
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|parentPermission
operator|!=
literal|null
condition|)
block|{
name|parent
operator|=
name|parentPermission
operator|.
name|map
operator|.
name|get
argument_list|(
name|provider
argument_list|)
expr_stmt|;
block|}
return|return
operator|(
name|parent
operator|==
literal|null
operator|)
condition|?
name|TreePermission
operator|.
name|EMPTY
else|:
name|parent
return|;
block|}
block|}
comment|//-----------------------------------------------< RepositoryPermission>---
comment|/**      * {@code RepositoryPermission} implementation that wraps multiple implementations.      */
specifier|private
specifier|final
class|class
name|CompositeRepositoryPermission
implements|implements
name|RepositoryPermission
block|{
annotation|@
name|Override
specifier|public
name|boolean
name|isGranted
parameter_list|(
name|long
name|repositoryPermissions
parameter_list|)
block|{
name|boolean
name|isGranted
init|=
literal|false
decl_stmt|;
name|long
name|coveredPermissions
init|=
name|Permissions
operator|.
name|NO_PERMISSION
decl_stmt|;
for|for
control|(
name|AggregatedPermissionProvider
name|aggregatedPermissionProvider
range|:
name|pps
control|)
block|{
name|long
name|supportedPermissions
init|=
name|aggregatedPermissionProvider
operator|.
name|supportedPermissions
argument_list|(
literal|null
argument_list|,
literal|null
argument_list|,
name|repositoryPermissions
argument_list|)
decl_stmt|;
if|if
condition|(
name|doEvaluate
argument_list|(
name|supportedPermissions
argument_list|)
condition|)
block|{
name|isGranted
operator|=
name|aggregatedPermissionProvider
operator|.
name|getRepositoryPermission
argument_list|()
operator|.
name|isGranted
argument_list|(
name|supportedPermissions
argument_list|)
expr_stmt|;
name|coveredPermissions
operator||=
name|supportedPermissions
expr_stmt|;
if|if
condition|(
operator|!
name|isGranted
condition|)
block|{
break|break;
block|}
block|}
block|}
return|return
name|isGranted
operator|&&
name|coveredPermissions
operator|==
name|repositoryPermissions
return|;
block|}
block|}
block|}
end_class

end_unit

