begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|jcr
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|Node
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|test
operator|.
name|AbstractJCRTest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Ignore
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_comment
comment|/**  * MoveTest... TODO  */
end_comment

begin_class
specifier|public
class|class
name|MoveTest
extends|extends
name|AbstractJCRTest
block|{
specifier|private
name|void
name|move
parameter_list|(
name|String
name|src
parameter_list|,
name|String
name|dest
parameter_list|,
name|boolean
name|save
parameter_list|)
throws|throws
name|Exception
block|{
name|superuser
operator|.
name|move
argument_list|(
name|src
argument_list|,
name|dest
argument_list|)
expr_stmt|;
if|if
condition|(
name|save
condition|)
block|{
name|superuser
operator|.
name|save
argument_list|()
expr_stmt|;
block|}
block|}
annotation|@
name|Ignore
argument_list|(
literal|"OAK-606"
argument_list|)
annotation|@
name|Test
specifier|public
name|void
name|testRename
parameter_list|()
throws|throws
name|Exception
block|{
name|Node
name|node1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
name|nodeName1
argument_list|)
decl_stmt|;
name|superuser
operator|.
name|save
argument_list|()
expr_stmt|;
name|String
name|destPath
init|=
name|testRoot
operator|+
literal|'/'
operator|+
name|nodeName2
decl_stmt|;
name|move
argument_list|(
name|node1
operator|.
name|getPath
argument_list|()
argument_list|,
name|destPath
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|destPath
argument_list|,
name|node1
operator|.
name|getPath
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Ignore
argument_list|(
literal|"OAK-607"
argument_list|)
annotation|@
name|Test
specifier|public
name|void
name|testRenameNewNode
parameter_list|()
throws|throws
name|Exception
block|{
name|Node
name|node1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
name|nodeName1
argument_list|)
decl_stmt|;
name|String
name|destPath
init|=
name|testRoot
operator|+
literal|'/'
operator|+
name|nodeName2
decl_stmt|;
name|move
argument_list|(
name|node1
operator|.
name|getPath
argument_list|()
argument_list|,
name|destPath
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|destPath
argument_list|,
name|node1
operator|.
name|getPath
argument_list|()
argument_list|)
expr_stmt|;
name|superuser
operator|.
name|save
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
name|destPath
argument_list|,
name|node1
operator|.
name|getPath
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Ignore
argument_list|(
literal|"OAK-606"
argument_list|)
annotation|@
name|Test
specifier|public
name|void
name|testMove
parameter_list|()
throws|throws
name|Exception
block|{
name|Node
name|node1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
name|nodeName1
argument_list|)
decl_stmt|;
name|Node
name|node2
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
name|nodeName2
argument_list|)
decl_stmt|;
name|superuser
operator|.
name|save
argument_list|()
expr_stmt|;
name|String
name|destPath
init|=
name|node2
operator|.
name|getPath
argument_list|()
operator|+
literal|'/'
operator|+
name|nodeName1
decl_stmt|;
name|move
argument_list|(
name|node1
operator|.
name|getPath
argument_list|()
argument_list|,
name|destPath
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|destPath
argument_list|,
name|node1
operator|.
name|getPath
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Ignore
argument_list|(
literal|"OAK-607"
argument_list|)
annotation|@
name|Test
specifier|public
name|void
name|testMoveNewNode
parameter_list|()
throws|throws
name|Exception
block|{
name|Node
name|node1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
name|nodeName1
argument_list|)
decl_stmt|;
name|Node
name|node2
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
name|nodeName2
argument_list|)
decl_stmt|;
name|String
name|destPath
init|=
name|node2
operator|.
name|getPath
argument_list|()
operator|+
literal|'/'
operator|+
name|nodeName1
decl_stmt|;
name|move
argument_list|(
name|node1
operator|.
name|getPath
argument_list|()
argument_list|,
name|destPath
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|destPath
argument_list|,
name|node1
operator|.
name|getPath
argument_list|()
argument_list|)
expr_stmt|;
name|superuser
operator|.
name|save
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
name|destPath
argument_list|,
name|node1
operator|.
name|getPath
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

