begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|security
operator|.
name|authentication
operator|.
name|ldap
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|Credentials
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|SimpleCredentials
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|security
operator|.
name|auth
operator|.
name|Subject
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|security
operator|.
name|auth
operator|.
name|callback
operator|.
name|CallbackHandler
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|security
operator|.
name|auth
operator|.
name|login
operator|.
name|LoginException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|authentication
operator|.
name|external
operator|.
name|ExternalLoginModule
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|security
operator|.
name|authentication
operator|.
name|external
operator|.
name|ExternalUser
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_class
specifier|public
specifier|final
class|class
name|LdapLoginModule
extends|extends
name|ExternalLoginModule
block|{
specifier|private
specifier|static
specifier|final
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|ExternalLoginModule
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|private
name|Credentials
name|credentials
decl_stmt|;
specifier|private
name|LdapUser
name|ldapUser
decl_stmt|;
specifier|private
name|boolean
name|success
decl_stmt|;
specifier|private
name|LdapSearch
name|search
decl_stmt|;
annotation|@
name|Override
specifier|public
name|void
name|initialize
parameter_list|(
name|Subject
name|subject
parameter_list|,
name|CallbackHandler
name|callbackHandler
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|?
argument_list|>
name|sharedState
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|?
argument_list|>
name|options
parameter_list|)
block|{
name|super
operator|.
name|initialize
argument_list|(
name|subject
argument_list|,
name|callbackHandler
argument_list|,
name|sharedState
argument_list|,
name|options
argument_list|)
expr_stmt|;
comment|//TODO
name|this
operator|.
name|search
operator|=
operator|new
name|JndiLdapSearch
argument_list|(
operator|new
name|LdapSettings
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|protected
name|boolean
name|loginSucceeded
parameter_list|()
block|{
return|return
name|this
operator|.
name|success
return|;
block|}
annotation|@
name|Override
specifier|protected
name|ExternalUser
name|getExternalUser
parameter_list|()
block|{
if|if
condition|(
name|this
operator|.
name|ldapUser
operator|==
literal|null
condition|)
block|{
name|Credentials
name|creds
init|=
name|getCredentials
argument_list|()
decl_stmt|;
if|if
condition|(
name|creds
operator|instanceof
name|SimpleCredentials
condition|)
block|{
name|String
name|uid
init|=
operator|(
operator|(
name|SimpleCredentials
operator|)
name|creds
operator|)
operator|.
name|getUserID
argument_list|()
decl_stmt|;
name|char
index|[]
name|pwd
init|=
operator|(
operator|(
name|SimpleCredentials
operator|)
name|creds
operator|)
operator|.
name|getPassword
argument_list|()
decl_stmt|;
name|this
operator|.
name|ldapUser
operator|=
operator|new
name|LdapUser
argument_list|(
name|uid
argument_list|,
operator|new
name|String
argument_list|(
name|pwd
argument_list|)
argument_list|,
name|this
operator|.
name|search
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|this
operator|.
name|ldapUser
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|login
parameter_list|()
throws|throws
name|LoginException
block|{
name|getExternalUser
argument_list|()
expr_stmt|;
if|if
condition|(
name|this
operator|.
name|ldapUser
operator|!=
literal|null
operator|&&
name|this
operator|.
name|search
operator|.
name|findUser
argument_list|(
name|this
operator|.
name|ldapUser
argument_list|)
condition|)
block|{
name|this
operator|.
name|search
operator|.
name|authenticate
argument_list|(
name|this
operator|.
name|ldapUser
argument_list|)
expr_stmt|;
name|this
operator|.
name|success
operator|=
literal|true
expr_stmt|;
block|}
return|return
name|this
operator|.
name|success
return|;
block|}
annotation|@
name|Override
specifier|protected
name|Credentials
name|getCredentials
parameter_list|()
block|{
if|if
condition|(
name|this
operator|.
name|credentials
operator|==
literal|null
condition|)
block|{
name|this
operator|.
name|credentials
operator|=
name|super
operator|.
name|getCredentials
argument_list|()
expr_stmt|;
block|}
return|return
name|this
operator|.
name|credentials
return|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|clearState
parameter_list|()
block|{
name|super
operator|.
name|clearState
argument_list|()
expr_stmt|;
name|this
operator|.
name|success
operator|=
literal|false
expr_stmt|;
name|this
operator|.
name|credentials
operator|=
literal|null
expr_stmt|;
name|this
operator|.
name|ldapUser
operator|=
literal|null
expr_stmt|;
name|this
operator|.
name|search
operator|=
literal|null
expr_stmt|;
block|}
block|}
end_class

end_unit

