begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|jcr
operator|.
name|query
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|core
operator|.
name|query
operator|.
name|AbstractQueryTest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|Type
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|Node
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|RepositoryException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|Session
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|Value
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|query
operator|.
name|Query
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|query
operator|.
name|QueryManager
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|query
operator|.
name|QueryResult
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|query
operator|.
name|Row
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|query
operator|.
name|RowIterator
import|;
end_import

begin_comment
comment|/**  * Test for faceting capabilities via JCR API  */
end_comment

begin_class
specifier|public
class|class
name|FacetTest
extends|extends
name|AbstractQueryTest
block|{
specifier|public
name|void
name|testFacetRetrieval
parameter_list|()
throws|throws
name|Exception
block|{
name|Session
name|session
init|=
name|superuser
decl_stmt|;
name|Node
name|n1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node1"
argument_list|)
decl_stmt|;
name|n1
operator|.
name|setProperty
argument_list|(
literal|"text"
argument_list|,
literal|"hello"
argument_list|)
expr_stmt|;
name|Node
name|n2
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node2"
argument_list|)
decl_stmt|;
name|n2
operator|.
name|setProperty
argument_list|(
literal|"text"
argument_list|,
literal|"hallo"
argument_list|)
expr_stmt|;
name|Node
name|n3
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node3"
argument_list|)
decl_stmt|;
name|n3
operator|.
name|setProperty
argument_list|(
literal|"text"
argument_list|,
literal|"oh hallo"
argument_list|)
expr_stmt|;
name|session
operator|.
name|save
argument_list|()
expr_stmt|;
name|QueryManager
name|qm
init|=
name|session
operator|.
name|getWorkspace
argument_list|()
operator|.
name|getQueryManager
argument_list|()
decl_stmt|;
name|String
name|sql2
init|=
literal|"select [jcr:path], [rep:facet(text)] from [nt:base] "
operator|+
literal|"where contains([text], 'hello OR hallo') order by [jcr:path]"
decl_stmt|;
name|Query
name|q
init|=
name|qm
operator|.
name|createQuery
argument_list|(
name|sql2
argument_list|,
name|Query
operator|.
name|JCR_SQL2
argument_list|)
decl_stmt|;
name|QueryResult
name|result
init|=
name|q
operator|.
name|execute
argument_list|()
decl_stmt|;
name|String
name|facetResult
init|=
literal|"text:[hallo (1), hello (1), oh hallo (1)]"
decl_stmt|;
name|assertEquals
argument_list|(
name|facetResult
operator|+
literal|", "
operator|+
name|facetResult
operator|+
literal|", "
operator|+
name|facetResult
argument_list|,
name|getResult
argument_list|(
name|result
argument_list|,
literal|"rep:facet(text)"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testFacetRetrievalMV
parameter_list|()
throws|throws
name|Exception
block|{
name|Session
name|session
init|=
name|superuser
decl_stmt|;
name|Node
name|n1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node1"
argument_list|)
decl_stmt|;
name|n1
operator|.
name|setProperty
argument_list|(
literal|"jcr:title"
argument_list|,
literal|"apache jackrabbit oak"
argument_list|)
expr_stmt|;
name|n1
operator|.
name|setProperty
argument_list|(
literal|"tags"
argument_list|,
operator|new
name|String
index|[]
block|{
literal|"software"
block|,
literal|"repository"
block|,
literal|"apache"
block|}
argument_list|)
expr_stmt|;
name|Node
name|n2
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node2"
argument_list|)
decl_stmt|;
name|n2
operator|.
name|setProperty
argument_list|(
literal|"jcr:title"
argument_list|,
literal|"oak furniture"
argument_list|)
expr_stmt|;
name|n2
operator|.
name|setProperty
argument_list|(
literal|"tags"
argument_list|,
literal|"furniture"
argument_list|)
expr_stmt|;
name|Node
name|n3
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node3"
argument_list|)
decl_stmt|;
name|n3
operator|.
name|setProperty
argument_list|(
literal|"jcr:title"
argument_list|,
literal|"oak cosmetics"
argument_list|)
expr_stmt|;
name|n3
operator|.
name|setProperty
argument_list|(
literal|"tags"
argument_list|,
literal|"cosmetics"
argument_list|)
expr_stmt|;
name|Node
name|n4
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node4"
argument_list|)
decl_stmt|;
name|n4
operator|.
name|setProperty
argument_list|(
literal|"jcr:title"
argument_list|,
literal|"oak and aem"
argument_list|)
expr_stmt|;
name|n4
operator|.
name|setProperty
argument_list|(
literal|"tags"
argument_list|,
operator|new
name|String
index|[]
block|{
literal|"software"
block|,
literal|"repository"
block|,
literal|"aem"
block|}
argument_list|)
expr_stmt|;
name|session
operator|.
name|save
argument_list|()
expr_stmt|;
name|QueryManager
name|qm
init|=
name|session
operator|.
name|getWorkspace
argument_list|()
operator|.
name|getQueryManager
argument_list|()
decl_stmt|;
name|String
name|sql2
init|=
literal|"select [jcr:path], [rep:facet(tags)] from [nt:base] "
operator|+
literal|"where contains([jcr:title], 'oak') order by [jcr:path]"
decl_stmt|;
name|Query
name|q
init|=
name|qm
operator|.
name|createQuery
argument_list|(
name|sql2
argument_list|,
name|Query
operator|.
name|JCR_SQL2
argument_list|)
decl_stmt|;
name|QueryResult
name|result
init|=
name|q
operator|.
name|execute
argument_list|()
decl_stmt|;
name|String
name|facetResult
init|=
literal|"tags:[repository (2), software (2), aem (1), apache (1), cosmetics (1), furniture (1)], tags:[repository (2), software (2), aem (1), apache (1), cosmetics (1), furniture (1)], tags:[repository (2), software (2), aem (1), apache (1), cosmetics (1), furniture (1)], tags:[repository (2), software (2), aem (1), apache (1), cosmetics (1), furniture (1)]"
decl_stmt|;
name|assertEquals
argument_list|(
name|facetResult
argument_list|,
name|getResult
argument_list|(
name|result
argument_list|,
literal|"rep:facet(tags)"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testFacetRetrievalWithAnonymousUser
parameter_list|()
throws|throws
name|Exception
block|{
name|Session
name|session
init|=
name|superuser
decl_stmt|;
name|Node
name|n1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node1"
argument_list|)
decl_stmt|;
name|n1
operator|.
name|setProperty
argument_list|(
literal|"text"
argument_list|,
literal|"hello"
argument_list|)
expr_stmt|;
name|Node
name|n2
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node2"
argument_list|)
decl_stmt|;
name|n2
operator|.
name|setProperty
argument_list|(
literal|"text"
argument_list|,
literal|"hallo"
argument_list|)
expr_stmt|;
name|Node
name|n3
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node3"
argument_list|)
decl_stmt|;
name|n3
operator|.
name|setProperty
argument_list|(
literal|"text"
argument_list|,
literal|"oh hallo"
argument_list|)
expr_stmt|;
name|session
operator|.
name|save
argument_list|()
expr_stmt|;
name|session
operator|=
name|getHelper
argument_list|()
operator|.
name|getReadOnlySession
argument_list|()
expr_stmt|;
name|QueryManager
name|qm
init|=
name|session
operator|.
name|getWorkspace
argument_list|()
operator|.
name|getQueryManager
argument_list|()
decl_stmt|;
name|String
name|sql2
init|=
literal|"select [jcr:path], [rep:facet(text)] from [nt:base] "
operator|+
literal|"where contains([text], 'hello OR hallo') order by [jcr:path]"
decl_stmt|;
name|Query
name|q
init|=
name|qm
operator|.
name|createQuery
argument_list|(
name|sql2
argument_list|,
name|Query
operator|.
name|JCR_SQL2
argument_list|)
decl_stmt|;
name|QueryResult
name|result
init|=
name|q
operator|.
name|execute
argument_list|()
decl_stmt|;
name|String
name|facetResult
init|=
literal|"text:[hallo (1), hello (1), oh hallo (1)]"
decl_stmt|;
name|assertEquals
argument_list|(
name|facetResult
operator|+
literal|", "
operator|+
name|facetResult
operator|+
literal|", "
operator|+
name|facetResult
argument_list|,
name|getResult
argument_list|(
name|result
argument_list|,
literal|"rep:facet(text)"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testFacetRetrieval2
parameter_list|()
throws|throws
name|Exception
block|{
name|Session
name|session
init|=
name|superuser
decl_stmt|;
name|Node
name|n1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node1"
argument_list|)
decl_stmt|;
name|String
name|pn
init|=
literal|"jcr:title"
decl_stmt|;
name|n1
operator|.
name|setProperty
argument_list|(
name|pn
argument_list|,
literal|"hello"
argument_list|)
expr_stmt|;
name|Node
name|n2
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node2"
argument_list|)
decl_stmt|;
name|n2
operator|.
name|setProperty
argument_list|(
name|pn
argument_list|,
literal|"hallo"
argument_list|)
expr_stmt|;
name|Node
name|n3
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node3"
argument_list|)
decl_stmt|;
name|n3
operator|.
name|setProperty
argument_list|(
name|pn
argument_list|,
literal|"oh hallo"
argument_list|)
expr_stmt|;
name|session
operator|.
name|save
argument_list|()
expr_stmt|;
name|QueryManager
name|qm
init|=
name|session
operator|.
name|getWorkspace
argument_list|()
operator|.
name|getQueryManager
argument_list|()
decl_stmt|;
name|String
name|sql2
init|=
literal|"select [jcr:path], [rep:facet("
operator|+
name|pn
operator|+
literal|")] from [nt:base] "
operator|+
literal|"where contains(["
operator|+
name|pn
operator|+
literal|"], 'hallo') order by [jcr:path]"
decl_stmt|;
name|Query
name|q
init|=
name|qm
operator|.
name|createQuery
argument_list|(
name|sql2
argument_list|,
name|Query
operator|.
name|JCR_SQL2
argument_list|)
decl_stmt|;
name|QueryResult
name|result
init|=
name|q
operator|.
name|execute
argument_list|()
decl_stmt|;
name|String
name|facetResult
init|=
name|pn
operator|+
literal|":[hallo (1), oh hallo (1)]"
decl_stmt|;
name|assertEquals
argument_list|(
name|facetResult
operator|+
literal|", "
operator|+
name|facetResult
argument_list|,
name|getResult
argument_list|(
name|result
argument_list|,
literal|"rep:facet("
operator|+
name|pn
operator|+
literal|")"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testMultipleFacetsRetrieval
parameter_list|()
throws|throws
name|Exception
block|{
name|Session
name|session
init|=
name|superuser
decl_stmt|;
name|Node
name|n1
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node1"
argument_list|)
decl_stmt|;
name|String
name|pn
init|=
literal|"jcr:title"
decl_stmt|;
name|String
name|pn2
init|=
literal|"jcr:description"
decl_stmt|;
name|n1
operator|.
name|setProperty
argument_list|(
name|pn
argument_list|,
literal|"hello"
argument_list|)
expr_stmt|;
name|n1
operator|.
name|setProperty
argument_list|(
name|pn2
argument_list|,
literal|"a"
argument_list|)
expr_stmt|;
name|Node
name|n2
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node2"
argument_list|)
decl_stmt|;
name|n2
operator|.
name|setProperty
argument_list|(
name|pn
argument_list|,
literal|"hallo"
argument_list|)
expr_stmt|;
name|n2
operator|.
name|setProperty
argument_list|(
name|pn2
argument_list|,
literal|"b"
argument_list|)
expr_stmt|;
name|Node
name|n3
init|=
name|testRootNode
operator|.
name|addNode
argument_list|(
literal|"node3"
argument_list|)
decl_stmt|;
name|n3
operator|.
name|setProperty
argument_list|(
name|pn
argument_list|,
literal|"oh hallo"
argument_list|)
expr_stmt|;
name|n3
operator|.
name|setProperty
argument_list|(
name|pn2
argument_list|,
literal|"a"
argument_list|)
expr_stmt|;
name|session
operator|.
name|save
argument_list|()
expr_stmt|;
name|QueryManager
name|qm
init|=
name|session
operator|.
name|getWorkspace
argument_list|()
operator|.
name|getQueryManager
argument_list|()
decl_stmt|;
name|String
name|sql2
init|=
literal|"select [jcr:path], [rep:facet("
operator|+
name|pn
operator|+
literal|")], [rep:facet("
operator|+
name|pn2
operator|+
literal|")] from [nt:base] "
operator|+
literal|"where contains(["
operator|+
name|pn
operator|+
literal|"], 'hallo') order by [jcr:path]"
decl_stmt|;
name|Query
name|q
init|=
name|qm
operator|.
name|createQuery
argument_list|(
name|sql2
argument_list|,
name|Query
operator|.
name|JCR_SQL2
argument_list|)
decl_stmt|;
name|QueryResult
name|result
init|=
name|q
operator|.
name|execute
argument_list|()
decl_stmt|;
name|String
name|facetResult
init|=
name|pn
operator|+
literal|":[hallo (1), oh hallo (1)], "
operator|+
name|pn2
operator|+
literal|":[a (1), b (1)], "
operator|+
name|pn
operator|+
literal|":[hallo (1), oh hallo (1)], "
operator|+
name|pn2
operator|+
literal|":[a (1), b (1)]"
decl_stmt|;
name|assertEquals
argument_list|(
name|facetResult
argument_list|,
name|getResult
argument_list|(
name|result
argument_list|,
literal|"rep:facet("
operator|+
name|pn
operator|+
literal|")"
argument_list|,
literal|"rep:facet("
operator|+
name|pn2
operator|+
literal|")"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|static
name|String
name|getResult
parameter_list|(
name|QueryResult
name|result
parameter_list|,
name|String
modifier|...
name|propertyNames
parameter_list|)
throws|throws
name|RepositoryException
block|{
name|StringBuilder
name|buff
init|=
operator|new
name|StringBuilder
argument_list|()
decl_stmt|;
name|RowIterator
name|it
init|=
name|result
operator|.
name|getRows
argument_list|()
decl_stmt|;
while|while
condition|(
name|it
operator|.
name|hasNext
argument_list|()
condition|)
block|{
name|Row
name|row
init|=
name|it
operator|.
name|nextRow
argument_list|()
decl_stmt|;
for|for
control|(
name|String
name|propertyName
range|:
name|propertyNames
control|)
block|{
name|Value
name|value
init|=
name|row
operator|.
name|getValue
argument_list|(
name|propertyName
argument_list|)
decl_stmt|;
if|if
condition|(
name|value
operator|!=
literal|null
condition|)
block|{
if|if
condition|(
name|buff
operator|.
name|length
argument_list|()
operator|>
literal|0
condition|)
block|{
name|buff
operator|.
name|append
argument_list|(
literal|", "
argument_list|)
expr_stmt|;
block|}
name|buff
operator|.
name|append
argument_list|(
name|value
operator|.
name|getString
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
block|}
return|return
name|buff
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
end_class

end_unit

