begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|jcr
operator|.
name|security
operator|.
name|authorization
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|RepositoryException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jcr
operator|.
name|Session
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Ignore
import|;
end_import

begin_comment
comment|/**  * Permission evaluation tests for move operations.  */
end_comment

begin_class
annotation|@
name|Ignore
argument_list|(
literal|"OAK-710 : permission validator doesn't detect move"
argument_list|)
specifier|public
class|class
name|WorkspaceMoveTest
extends|extends
name|AbstractMoveTest
block|{
annotation|@
name|Override
specifier|protected
name|void
name|move
parameter_list|(
name|String
name|source
parameter_list|,
name|String
name|dest
parameter_list|)
throws|throws
name|RepositoryException
block|{
name|move
argument_list|(
name|source
argument_list|,
name|dest
argument_list|,
name|testSession
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|move
parameter_list|(
name|String
name|source
parameter_list|,
name|String
name|dest
parameter_list|,
name|Session
name|session
parameter_list|)
throws|throws
name|RepositoryException
block|{
name|session
operator|.
name|getWorkspace
argument_list|()
operator|.
name|move
argument_list|(
name|source
argument_list|,
name|dest
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

