begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|observation
operator|.
name|filter
package|;
end_package

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Preconditions
operator|.
name|checkNotNull
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Nonnull
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|api
operator|.
name|PropertyState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|commons
operator|.
name|PathUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|core
operator|.
name|ImmutableTree
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|plugins
operator|.
name|observation
operator|.
name|filter
operator|.
name|EventGenerator
operator|.
name|Filter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|jackrabbit
operator|.
name|oak
operator|.
name|spi
operator|.
name|state
operator|.
name|NodeState
import|;
end_import

begin_comment
comment|/**  * {@code EventTypeFilter} filters based on the path of the<em>associated parent node</em> as  * defined by {@link javax.jcr.observation.ObservationManager#addEventListener(         javax.jcr.observation.EventListener, int, String, boolean, String[], String[], boolean)         ObservationManager.addEventListener()}.  */
end_comment

begin_class
specifier|public
class|class
name|PathFilter
implements|implements
name|Filter
block|{
specifier|private
specifier|final
name|ImmutableTree
name|beforeTree
decl_stmt|;
specifier|private
specifier|final
name|ImmutableTree
name|afterTree
decl_stmt|;
specifier|private
specifier|final
name|String
name|path
decl_stmt|;
specifier|private
specifier|final
name|boolean
name|deep
decl_stmt|;
comment|/**      * Create a new {@code Filter} instance that includes an event when the path of the      * associated parent node matches the one of this filter or - when the {@code deep}      * flag is set - is a descendant of the path of this filter.      *      * @param beforeTree  associated parent before state      * @param afterTree   associated parent after state      * @param path        path to match      */
specifier|public
name|PathFilter
parameter_list|(
annotation|@
name|Nonnull
name|ImmutableTree
name|beforeTree
parameter_list|,
annotation|@
name|Nonnull
name|ImmutableTree
name|afterTree
parameter_list|,
annotation|@
name|Nonnull
name|String
name|path
parameter_list|,
name|boolean
name|deep
parameter_list|)
block|{
name|this
operator|.
name|beforeTree
operator|=
name|checkNotNull
argument_list|(
name|beforeTree
argument_list|)
expr_stmt|;
name|this
operator|.
name|afterTree
operator|=
name|checkNotNull
argument_list|(
name|afterTree
argument_list|)
expr_stmt|;
name|this
operator|.
name|path
operator|=
name|checkNotNull
argument_list|(
name|path
argument_list|)
expr_stmt|;
name|this
operator|.
name|deep
operator|=
name|deep
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|includeAdd
parameter_list|(
name|PropertyState
name|after
parameter_list|)
block|{
return|return
name|includeByPath
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|includeChange
parameter_list|(
name|PropertyState
name|before
parameter_list|,
name|PropertyState
name|after
parameter_list|)
block|{
return|return
name|includeByPath
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|includeDelete
parameter_list|(
name|PropertyState
name|before
parameter_list|)
block|{
return|return
name|includeByPath
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|includeAdd
parameter_list|(
name|String
name|name
parameter_list|,
name|NodeState
name|after
parameter_list|)
block|{
return|return
name|includeByPath
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|includeChange
parameter_list|(
name|String
name|name
parameter_list|,
name|NodeState
name|before
parameter_list|,
name|NodeState
name|after
parameter_list|)
block|{
return|return
name|includeByPath
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|includeDelete
parameter_list|(
name|String
name|name
parameter_list|,
name|NodeState
name|before
parameter_list|)
block|{
return|return
name|includeByPath
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|includeMove
parameter_list|(
name|String
name|sourcePath
parameter_list|,
name|String
name|destPath
parameter_list|,
name|NodeState
name|moved
parameter_list|)
block|{
return|return
name|includeByPath
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|Filter
name|create
parameter_list|(
name|String
name|name
parameter_list|,
name|NodeState
name|before
parameter_list|,
name|NodeState
name|after
parameter_list|)
block|{
if|if
condition|(
name|includeChildren
argument_list|(
name|name
argument_list|)
condition|)
block|{
return|return
operator|new
name|PathFilter
argument_list|(
name|beforeTree
argument_list|,
name|afterTree
operator|.
name|getChild
argument_list|(
name|name
argument_list|)
argument_list|,
name|path
argument_list|,
name|deep
argument_list|)
return|;
block|}
else|else
block|{
return|return
literal|null
return|;
block|}
block|}
comment|//------------------------------------------------------------< private>---
specifier|private
name|boolean
name|includeByPath
parameter_list|()
block|{
name|String
name|path
init|=
name|afterTree
operator|.
name|exists
argument_list|()
condition|?
name|afterTree
operator|.
name|getPath
argument_list|()
else|:
name|beforeTree
operator|.
name|getPath
argument_list|()
decl_stmt|;
name|boolean
name|equalPaths
init|=
name|this
operator|.
name|path
operator|.
name|equals
argument_list|(
name|path
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|deep
operator|&&
operator|!
name|equalPaths
condition|)
block|{
return|return
literal|false
return|;
block|}
if|if
condition|(
name|deep
operator|&&
operator|!
operator|(
name|PathUtils
operator|.
name|isAncestor
argument_list|(
name|this
operator|.
name|path
argument_list|,
name|path
argument_list|)
operator|||
name|equalPaths
operator|)
condition|)
block|{
return|return
literal|false
return|;
block|}
return|return
literal|true
return|;
block|}
specifier|private
name|boolean
name|includeChildren
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|String
name|path
init|=
name|afterTree
operator|.
name|exists
argument_list|()
condition|?
name|PathUtils
operator|.
name|concat
argument_list|(
name|afterTree
operator|.
name|getPath
argument_list|()
argument_list|,
name|name
argument_list|)
else|:
name|PathUtils
operator|.
name|concat
argument_list|(
name|beforeTree
operator|.
name|getPath
argument_list|()
argument_list|,
name|name
argument_list|)
decl_stmt|;
return|return
name|PathUtils
operator|.
name|isAncestor
argument_list|(
name|path
argument_list|,
name|this
operator|.
name|path
argument_list|)
operator|||
name|path
operator|.
name|equals
argument_list|(
operator|(
name|this
operator|.
name|path
operator|)
argument_list|)
operator|||
name|deep
operator|&&
name|PathUtils
operator|.
name|isAncestor
argument_list|(
name|this
operator|.
name|path
argument_list|,
name|path
argument_list|)
return|;
block|}
block|}
end_class

end_unit

